server:
    port: 8765
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowercase-service-id: true
      routes:
        - id: ms-client
          uri: lb://ms-client
          predicates:
            - Path=/ms-client/clients/**
        - id: ms-card
          uri: lb://ms-card
          predicates:
            - Path=/ms-card/cards/**
        - id: ms-credit-assessor
          uri: lb://ms-credit-assessor
          predicates:
            - Path=/ms-credit-assessor/assessors/**
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
