server:
  port: 0
spring:
  application:
    name: ms-card
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: ""
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mq:
  queues:
    card-issuance: card-issuance